[package]
name = "ssb-keyfile"
version = "0.1.2"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]
description = "Keyfile operations for ssb."
repository = "https://github.com/AljoschaMeyer/ssb-keyfile-rs"
readme = "README.md"
license = "GPL-3.0"

[dependencies]
ssb-common = "0.2.3"
regex = "0.2.6"
lazy_static = "1.0.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.10"
